name: climby
description: Climby - escalada de plastilina
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: 1.18.0
  shared_preferences: 2.2.2
  audioplayers: 5.2.1
  flutter_svg: 2.0.10+1

dev_dependencies:
  flutter_lints: 3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/character/
    - assets/holds/
    - assets/ui/
